on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  yarn:
    name: Run NPM and Node
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use the latest Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: yarn install

      - name: Run index.js
        run: node index.js
  npm:
    name: Run Yarn and Node
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use the latest Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm i

      - name: Run index.js
        run: node index.js
